### ISSUE TITLE
Consider providing normalize for consumption from garden

### ISSUE THREAD

**Issue by noonian** [powernoodle/cljc-normalize#1]
For users who already use garden to generate css, it would be useful to consume normalize as a "mixin" instead of as a string. You can do this now by building the vector yourself, but it requires looking at the source code to know which vars to include for all of normalize.

You could add a new var `normalize-garden` to hold the vector and refer to that from `normalize`. Alternatively,  you could rename `normalize` to `normalize-css` and use `normalize` for the vector.

```clojure
(def normalize
  [base
   html5
   links
   text
   embedded
   grouping
   forms
   tables])

(def normalize-css
  (css normalize))
```

Thanks for the port.

**Comment by niamu** [comment]
I think this is a solid improvement. Feel free to open up a pull request using the method in your sample code excerpt.

Otherwise, I'll get to it by Monday.
